org: diegoflores
service: api-cursos

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::321787585501:role/LabRole

package:
  individually: true
  patterns:
    - '!**/*.py'
    
functions:
  listar:
    handler: ListarCursos.lambda_handler
    package:
      patterns:
        - '!**/*.py'        # First exclude all Python files
        - 'ListarCursos.py'
    events:
      - http:
          path: /cursos/listar
          method: get
          cors: true
          integration: lambda
  buscar:
    handler: BuscarCurso.lambda_handler
    package:
      patterns:
        - '!**/*.py'      # First exclude all Python files
        - 'BuscarCurso.py'
    events:
      - http:
          path: /cursos/buscar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearCurso.lambda_handler
    package:
      patterns:
        - '!**/*.py'      # First exclude all Python files
        - 'CrearCurso.py'
    events:
      - http:
          path: /cursos/crear
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarCurso.lambda_handler
    package:
      patterns:
        - '!**/*.py'          # First exclude all Python files
        - 'ModificarCurso.py'
    events:
      - http:
          path: /cursos/modificar
          method: put
          cors: true
          integration: lambda
  eliminar:
    handler: EliminarCurso.lambda_handler
    package:
      patterns:
        - '!**/*.py'         # First exclude all Python files
        - 'EliminarCurso.py'
    events:
      - http:
          path: /cursos/eliminar
          method: delete
          cors: true
          integration: lambda
